import { HttpMethod, HttpParameterType } from "./enums";
export declare const HttpRequest: (url: string, method: HttpMethod) => any;
export declare const HttpGet: (url: string) => any;
export declare const HttpPut: (url: string) => any;
export declare const HttpPost: (url: string) => any;
export declare const HttpDelete: (url: string) => any;
export declare const HttpReceive: (...messages: {}) => any;
export declare const HttpResponse: (code: number) => any;
export declare const HttpParameter: (type: HttpParameterType, alias?: string) => any;
export declare const Path: (alias?: string) => any;
export declare const Body: (alias?: string) => any;
export declare const Query: (alias?: string) => any;
export declare const Ignore: (alias?: string) => any;
